import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        "on-primary": "#15267b",
        "surface-container-high": "#282a2d",
        "on-error": "#690005",
        "on-tertiary": "#00363e",
        "surface-tint": "#bac3ff",
        "secondary-fixed-dim": "#66d9cc",
        "on-tertiary-fixed": "#001f24",
        "on-secondary-fixed": "#00201d",
        "surface-container-lowest": "#0c0e11",
        "surface-container-low": "#1a1c1f",
        "on-tertiary-fixed-variant": "#004e59",
        "on-primary-fixed-variant": "#2f3f92",
        "tertiary": {
          DEFAULT: "#55d7ed",
          fixed: "#9eefff",
          "fixed-dim": "#55d7ed",
          container: "#006471",
        },
        "surface-variant": "#333538",
        "on-background": "#e2e2e6",
        "on-surface-variant": "#c5c5d4",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e2e2e6",
        "on-surface": "#e2e2e6",
        "primary-fixed-dim": "#bac3ff",
        "on-secondary-fixed-variant": "#005049",
        "surface-container": "#1e2023",
        "surface": "#111316",
        "on-primary-fixed": "#00105b",
        "surface-dim": "#111316",
        "secondary-fixed": "#84f5e8",
        "primary-container": "#4453a7",
        "on-primary-container": "#c9cfff",
        "surface-container-highest": "#333538",
        "on-secondary-container": "#00302b",
        "outline": "#8f909e",
        "inverse-on-surface": "#2f3034",
        "secondary-container": "#1ea296",
        "error-container": "#93000a",
        "surface-bright": "#37393d",
        "on-tertiary-container": "#64e3f9",
        "outline-variant": "#454652",
        "primary-fixed": "#dee0ff",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 15px -5px hsl(var(--primary) / 0.3)" },
          "50%": { boxShadow: "0 0 25px -5px hsl(var(--primary) / 0.5)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s ease-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
